### ISSUE TITLE
php_bfr.lo ==> error 1

### ISSUE THREAD

**Issue by tom9un** [mushorg/BFR#5]
<img width="805" alt="Screen Shot 2020-04-12 at 14 33 31" src="https://user-images.githubusercontent.com/33028642/79063383-a06e2600-7ccb-11ea-991a-216db5b99b4e.png">

**Comment by glaslos** [comment]
I don't think BFR still works with PHP5 🤔 try PHP7

**Comment by glaslos** [comment]
Also, please past the output as text instead of a screenshot...

**Comment by tom9un** [comment]
production@production:/opt/BFR$ sudo make
/bin/bash /opt/BFR/libtool --mode=compile cc -Werror -Wall -I. -I/opt/BFR -DPHP_ATOM_INC -I/opt/BFR/include -I/opt/BFR/main -I/opt/BFR -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/BFR/php_bfr.c -o php_bfr.lo 
 cc -Werror -Wall -I. -I/opt/BFR -DPHP_ATOM_INC -I/opt/BFR/include -I/opt/BFR/main -I/opt/BFR -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/BFR/php_bfr.c  -fPIC -DPIC -o .libs/php_bfr.o
/opt/BFR/php_bfr.c: In function 'zif_override_function':
/opt/BFR/php_bfr.c:123:41: error: expected ')' before 'TSRMLS_CC'
/opt/BFR/php_bfr.c:126:8: error: too few arguments to function 'zend_parse_parameters'
/usr/local/include/php/Zend/zend_API.h:298:14: note: declared here
/opt/BFR/php_bfr.c:139:72: error: expected ')' before 'TSRMLS_CC'
/opt/BFR/php_bfr.c:140:55: error: expected ')' before 'TSRMLS_CC'
/opt/BFR/php_bfr.c:147:30: error: 'TSRMLS_C' undeclared (first use in this function)
/opt/BFR/php_bfr.c:147:30: note: each undeclared identifier is reported only once for each function it appears in
/opt/BFR/php_bfr.c:147:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c:156:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c:175:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c:184:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c: In function 'zif_rename_function':
/opt/BFR/php_bfr.c:200:41: error: expected ')' before 'TSRMLS_CC'
/opt/BFR/php_bfr.c:202:8: error: too few arguments to function 'zend_parse_parameters'
/usr/local/include/php/Zend/zend_API.h:298:14: note: declared here
/opt/BFR/php_bfr.c:211:30: error: 'TSRMLS_C' undeclared (first use in this function)
/opt/BFR/php_bfr.c:211:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c:219:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c:230:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c:237:5: error: too many arguments to function 'get_active_function_name'
/usr/local/include/php/Zend/zend_execute.h:289:22: note: declared here
/opt/BFR/php_bfr.c: In function 'bfr_zend_startup':
/opt/BFR/php_bfr.c:253:2: error: implicit declaration of function 'TSRMLS_FETCH' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make: *** [php_bfr.lo] Error 1
production@production:/opt/BFR$

**Comment by tom9un** [comment]
installed php version :
production@production:/opt/BFR$ php -v
PHP 8.0.0-dev (cli) (built: Apr 12 2020 20:51:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
production@production:/opt/BFR$

**Comment by tom9un** [comment]
Solved with ...
sudo git clone -b PHP-7.0.7  https://github.com/php/php-src php7

but have new problem when running glastopf...like this...

production@production:/opt/myhoneypot$ sudo glastopf-runner

/usr/local/lib/python2.7/dist-packages/pkg_resources/py2_warn.py:21: UserWarning: Setuptools will stop working on Python 2
************************************************************
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
Please ensure you are installing
Setuptools using pip 9.x or later or pin to `setuptools<45`
in your environment.
If you have done those things and are still encountering
this message, please follow up at
https://bit.ly/setuptools-py2-warning.
************************************************************
  sys.version_info < (3,) and warnings.warn(pre + "*" * 60 + msg + "*" * 60)
Traceback (most recent call last):
  File "/usr/local/bin/glastopf-runner", line 4, in <module>
    __import__('pkg_resources').run_script('Glastopf==3.1.3.dev0', 'glastopf-runner')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Glastopf-3.1.3.dev0-py3.6.egg/EGG-INFO/scripts/glastopf-runner", line 11, in <module>
    from gevent.wsgi import WSGIServer
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/usr/local/lib/python2.7/dist-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/usr/local/lib/python2.7/dist-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named __hub_local

production@production:/opt/myhoneypot$

**Comment by glaslos** [comment]
I highly recommend to use Glastopfs successor SNARE: https://github.com/mushorg/snare
Did you consider using the Docker container instead of setting it up manually?

**Comment by tom9un** [comment]
i think glastopf have issues in requirements....i try with docker, invalid PGP signature...
